<Project>
    <PropertyGroup>
        <Authors>Defra</Authors>
        <TargetFramework>net10.0</TargetFramework>
        <Title>Defra .net database project</Title>
        <Description>Defra .net project templates</Description>
        <RepositoryType>git</RepositoryType>
        <PackageTags>api, postgres</PackageTags>
        <RepositoryUrl>https://github.com/defra/project-template</RepositoryUrl>
        <Copyright>Copyright © $([System.DateTime]::Now.ToString("yyyy")) Defra</Copyright>
        <PackageProjectUrl>https://www.gov.uk/government/organisations/department-for-environment-food-rural-affairs</PackageProjectUrl>
        <license>https://github.com/threenine/api-template/blob/master/LICENSE</license>
        <PackageIcon>icon.png</PackageIcon>
        <RootNamespace>Defra</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <Content Include="$(MSBuildThisFileDirectory)icon.png" Pack="true" PackagePath="/">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
</Project>