<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Using Include="Xunit"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Database\Database.csproj" />
    <ProjectReference Include="..\..\src\Entities\Entities.csproj" />
    <ProjectReference Include="..\..\src\Postgres\Postgres.csproj" />
  </ItemGroup>
</Project>