#file: noinspection UndefinedParamsPresent,UndefinedAction
name: 'Publish NuGet Packages'

on:
  push:
    tags:
      - '*.*.*'

concurrency:
  group: nuget-publish-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write

jobs:
  publish-nuget:
    name: 'Publish nuget'
    uses: ./.github/workflows/support-publish.yml
    with:
      version: ${{ github.ref_name }}
